language: node_js

dist: trusty

node_js:
  - 8
  - 9

cache:
  yarn: true
  directories: 
    - node_modules

stages:
  - "test"
  - ":ship to npm"

jobs:
  include:
    if: type IN (push, pull_request)
    - stage: "test"
