language: node_js
dist: trusty
node_js:
- 8
- 9
- 10
cache:
  yarn: true
  directories:
  - node_modules
stages:
- test
- deploy
notifications:
  email:
    on_success: change
    on_failure: always
jobs:
  include:
  - stage: test
    script: yarn test
    if: type IN (push, pull_request)
  - stage: deploy
    if: tag IS present
    deploy:
      skip_cleanup: true
      script: yarn build
      provider: npm
      email: lucien.benie@gmail.com
      api_key:
        secure: drYcfKsdHBDNQjCKgo2PHOTUVz1VQYkdT+x8+2GTK14tZwLNnfHJKt083FPFYH7FnFUE0of0coqtJtLp5tXZiNeDiuJg95r5attcq9JCKVJIYkeS3jalv+AuCEd9Qj64aQG/UC6wcThx3ZIIAp0Cb7Y5SZDJoUs0PWYk09kJpmEporsk9nxNOtV0GCilRkVlP94fga7jmNKnRLvn+22aO1ey5vWoMWi8hBMt6/BfEYVBA7iePPqWR/vEh29ZzhlBE5hFTlQQdhI15z/S1VlFolUInwgljVLd/7IwGze+p1aW8A1pAChN1VNjJU441sJap9YKzlh3Zoqs3+7X+zsnV0M8c4LEEioVTljHk0duucIV79wwIaom29my5dQTbynPLs9ON9J4Bs77KfBQHdtnQxBEsWElS7Ufw5lY34YTvwPcwgBGIePM8kOQ/uRNME0DgETwB9EmKJ6Af54U08MgBs8kMLF3QRYOpjFCchNR19cWrbxzGtPwdeC1rCCyi34x+3PxI1VwbA6LsMvrcjYblrkE8HnMl2U3dXn3hcIY5BZSChFgj0QrX3qIpInFtzmxE4bOylGsxKRAm7FtZVQ6K9o4RQRYuIUdtzY2FNO4Gz6NyIh2L2FrD5kLEDCBvxAY/H9nWGbcySqhaxA1rhVEbMZlULSTpRdgB2HjVOtvFAA=
      on:
        tags: true
        repo: lbenie/qselector
env:
  global:
    secure: axxQ9xbVZ3lhLJdZ3B4/ougsPDj/fwNhk/X5tDrbraZqUD32kBpiV9E6EeX3PoFiBv/DCfH1bhfCFtUGei532TGWpeTAToX7rSmd6gCd+LLQWZ/rI1zzBERoreTMCPT3U7GNblMMuCzgvauVzn5SLs9lgAHJYlZBm0PBmB2XCJNDRg06EEQpOpgc1vur7WR2BgMWy9ndRoXALPZj7xn97DznHvDlZsxrlRMafuwexogMoNp4wxz+uXLOQHaBhdtGy2MSJqI7RvosfQwt6F/qCI9KsoH9PDCtlWPBpwlMKVJPGz9sUUSnvZ4F14X6MfnicDYF7tMemL4nSxCldo48aBLVI9RbxHbz1M5HPx8afsMot0YQLMyd1MioSxXatwtHhzyzalvcmn50e9SvjdG4CeGi9iq43KH8yXOwQ0eaift6LzqmzgrHG4siWh8PWlKxKCymx6BaBIyGCltVC374Ft7UCYKovXaQd/zusUMQn6EJ2e43fOKG0pwpgvCXkGvKzlX7hw4sYKGiZ7LhrVCRvd0zATfY2Fee4ISjemc6VK1D+YfIqSB6qJFSz90FoQeUxPk6mzEGfXNfy4t5HfD0fSzxYhjla2Fadv2jU8nrNTWm0g3wy39yF5zOOzXtOQxbAzl+BG4+DyuBw06fUanp9N7kEcm/PJf0VnhWV0PN6Ig=
