language: node_js

dist: trusty

node_js:
  - 8
  - 9

cache:
  yarn: true
  directories: 
    - node_modules

stages:
  - "test"
  - ":ship to npm"

jobs:
  include:
    - stage: "test"
      dist: trusty
      script: "yarn test"